FROM node:14.17-alpine3.13 as base
WORKDIR /work
COPY package.json yarn.lock* ./
COPY packages/lib/package.json ./packages/lib/package.json

FROM base as deps
RUN yarn
ENV NODE_ENV=development
RUN sh -c "cat package.json"
RUN sh -c "ls -lA node_modules"
COPY . .
RUN yarn workspace @app/lib run build

FROM deps as graph
COPY --from=deps /work/packages/lib/build ./packages/lib/build
ENV PORT ${GRAPH_CONTAINER_PORT}
EXPOSE $PORT
CMD ["yarn", "dev:run:graph"]

FROM deps as realtime
COPY --from=deps /work/packages/lib/build ./packages/lib/build
ENV PORT ${REALTIME_HOST_PORT}
EXPOSE $PORT
CMD ["yarn", "dev:run:realtime"]

FROM deps as backend
COPY --from=deps /work/packages/lib/build ./packages/lib/build
ENV PORT ${BACKEND_CONTAINER_PORT}
EXPOSE $PORT
CMD ["yarn", "dev:run"]