FROM node:14.17-alpine3.13 

# NODE_ENV=production will not install devDependencies
ENV NODE_ENV=development

WORKDIR /work

COPY . .

RUN sh -c "ls -lA"

ENV PORT ${NODE_APP_CONTAINER_NAME_PORT}

# This does not actually expose anything, its only meant for reference purpose
EXPOSE $PORT

# WHen you start container this command will get executed
# You can override this during runtime if you want
CMD ["yarn", "dev:run"]