#cloud-config
groups:
  - docker
users:
  - default
  - name: docker-node
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    passwd: "hashed password here" # mkpasswd --method=SHA-512 --rounds=4096
    ssh_authorized_keys:
      - "rsa public key only, Azure does not accept ed25519 keys :("
    groups: docker
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - vim
  - neovim
runcmd:
  # install docker following the guide: https://docs.docker.com/install/linux/docker-ce/ubuntu/
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt -y update
  - sudo apt -y install docker-ce docker-ce-cli containerd.io
  - sudo systemctl enable docker
  - if ! [ -x "$(command -v task)" ]; then sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin ; fi

  # install docker-compose following the guide: https://docs.docker.com/compose/install/
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

# Restart is required so that the group assignment to docker-node user works and so later we no longer have to use 'sudo'
power_state:
  mode: reboot
  message: Restarting after installing docker & docker-compose